#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/rocket-donation
#    username: root
#    password: root157
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
# H2 Database Connection Properties
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
